
#端口号
server:
  port: 8010
  servlet:
    context-path: /
#数据库链接设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: zhangxian11
    #配置前端
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
#整合Mybatis
mybatis:
  #  扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: com.example.webserviceclic.pojo
  #  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml
#  多层级目录  mapper-locations: classpath:mapper/**/**.xml


